#!/usr/bin/env node
/**
 * Embeds plugin/**\/*.{zsh,bash,sh} into runtime/generated/plugin.ts so a
 * single-file binary can install the shell integration without shipping loose
 * files.  Keys are repo-relative paths, so extraction is a straight mkdir+write.
 *
 * Run after editing plugin/: `npm run gen` (both build scripts do it too).
 */

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = join(import.meta.dirname, "..");
const source = join(root, "plugin");
const target = join(root, "runtime", "generated", "plugin.ts");

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const files = walk(source)
  .filter((path) => /\.(zsh|bash|sh)$/.test(path))
  .sort();

const entries = files.map(
  (path) => `  ${JSON.stringify(relative(root, path))}: ${JSON.stringify(readFileSync(path, "utf8"))},`,
);

const contents = [
  "// Generated by scripts/gen-plugin.ts — do not edit by hand.",
  "// Source of truth: plugin/** (run `npm run gen` after editing).",
  "export const PLUGIN_FILES: Record<string, string> = {",
  ...entries,
  "};",
  "",
].join("\n");

mkdirSync(join(root, "runtime", "generated"), { recursive: true });
writeFileSync(target, contents, "utf8");
console.log(`embedded ${files.length} plugin files → runtime/generated/plugin.ts`);
