#!/usr/bin/env node
/**
 * Embeds plugin/zsh/*.zsh into runtime/generated/plugin.ts so a single-file
 * binary can install the shell integration without shipping loose files.
 *
 * Run after editing plugin/zsh/: `npm run gen` (build.sh does it too).
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const source = join(root, "plugin", "zsh");
const target = join(root, "runtime", "generated", "plugin.ts");

const files = readdirSync(source)
  .filter((name) => name.endsWith(".zsh"))
  .sort();

const entries = files.map(
  (name) => `  ${JSON.stringify(name)}: ${JSON.stringify(readFileSync(join(source, name), "utf8"))},`,
);

const contents = [
  "// Generated by scripts/gen-plugin.ts — do not edit by hand.",
  "// Source of truth: plugin/zsh/*.zsh (run `npm run gen` after editing).",
  "export const PLUGIN_FILES: Record<string, string> = {",
  ...entries,
  "};",
  "",
].join("\n");

mkdirSync(join(root, "runtime", "generated"), { recursive: true });
writeFileSync(target, contents, "utf8");
console.log(`embedded ${files.length} plugin files → runtime/generated/plugin.ts`);
